# Generated by Django 5.2.1 on 2025-05-31 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routine', '0003_slot_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='routine',
            name='batch',
            field=models.CharField(default='3-2', max_length=10),
        ),
    ]
