# Generated by Django 5.2 on 2025-06-19 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routine', '0004_routine_batch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='routine',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='routine',
            name='is_cancelled',
        ),
        migrations.RemoveField(
            model_name='routine',
            name='is_online',
        ),
        migrations.RemoveField(
            model_name='routine',
            name='status',
        ),
    ]
