# Generated by Django 5.1.7 on 2025-04-26 15:52

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0002_classschedule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classschedule',
            name='day',
        ),
        migrations.RemoveField(
            model_name='classschedule',
            name='room',
        ),
        migrations.AddField(
            model_name='classschedule',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Reschedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_online', models.BooleanField(default=False)),
                ('online_duration', models.IntegerField(blank=True, null=True)),
                ('room', models.CharField(blank=True, max_length=100, null=True)),
                ('new_start_time', models.TimeField(blank=True, null=True)),
                ('new_end_time', models.TimeField(blank=True, null=True)),
                ('class_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachers.classschedule')),
            ],
        ),
    ]
