# Generated by Django 5.2 on 2025-04-29 17:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0004_reschedule_selected_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reschedule',
            name='selected_day',
        ),
        migrations.AddField(
            model_name='reschedule',
            name='reschedule_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
