# Generated by Django 5.2 on 2025-05-29 15:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0005_remove_reschedule_selected_day_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reschedule',
            name='new_end_time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reschedule',
            name='new_start_time',
            field=models.TimeField(default='12:00:00'),
            preserve_default=False,
        ),
    ]
