# Generated by Django 5.2 on 2025-05-29 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0006_alter_reschedule_new_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reschedule',
            name='offline_duration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reschedule',
            name='new_end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reschedule',
            name='new_start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
