# Generated by Django 5.2 on 2025-06-01 03:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0007_reschedule_offline_duration_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_online', models.BooleanField()),
                ('online_duration', models.IntegerField(blank=True, null=True)),
                ('offline_duration', models.IntegerField(blank=True, null=True)),
                ('room', models.CharField(blank=True, max_length=50)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachers.teacher')),
            ],
        ),
    ]
