# Generated by Django 5.1.5 on 2025-06-01 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0008_extraclass'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExtraClass',
        ),
    ]
