# Generated by Django 5.2 on 2025-06-10 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0009_delete_extraclass'),
    ]

    operations = [
        migrations.AddField(
            model_name='classschedule',
            name='is_cancelled',
            field=models.BooleanField(default=False),
        ),
    ]
