# Generated by Django 5.2 on 2025-06-18 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0010_classschedule_is_cancelled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classschedule',
            name='is_cancelled',
        ),
    ]
