# Generated by Django 5.2 on 2025-06-18 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0011_remove_classschedule_is_cancelled'),
    ]

    operations = [
        migrations.AddField(
            model_name='classschedule',
            name='original_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
