# Generated by Django 5.2 on 2025-06-19 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_remove_course_teachers_alter_course_total_classes'),
        ('teachers', '0012_classschedule_original_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classschedule',
            name='subject',
        ),
        migrations.AddField(
            model_name='classschedule',
            name='class_type',
            field=models.CharField(choices=[('offline', 'Offline'), ('online', 'Online')], default='offline', max_length=10),
        ),
        migrations.AddField(
            model_name='classschedule',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.course'),
        ),
        migrations.AddField(
            model_name='classschedule',
            name='semester',
            field=models.CharField(default='3-2', max_length=10),
        ),
        migrations.AddField(
            model_name='classschedule',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('conducted', 'Conducted'), ('missed', 'Missed'), ('rescheduled', 'Rescheduled'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
