# Generated by Django 5.2 on 2025-06-20 03:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routine', '0005_remove_routine_created_at_and_more'),
        ('teachers', '0013_remove_classschedule_subject_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classschedule',
            name='room',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='routine.room'),
        ),
        migrations.AlterUniqueTogether(
            name='classschedule',
            unique_together={('room', 'date', 'start_time')},
        ),
    ]
