# Generated by Django 5.2 on 2025-06-20 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0014_classschedule_room_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='classschedule',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='classschedule',
            name='room',
        ),
    ]
