# Generated by Django 5.2 on 2025-06-20 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0016_classschedule_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classschedule',
            name='room',
        ),
    ]
