# Generated by Django 5.2 on 2025-06-20 04:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routine', '0005_remove_routine_created_at_and_more'),
        ('teachers', '0018_classschedule_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reschedule',
            name='offline_duration',
        ),
        migrations.RemoveField(
            model_name='reschedule',
            name='online_duration',
        ),
        migrations.AddField(
            model_name='reschedule',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('conducted', 'Conducted'), ('cancelled', 'Cancelled')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='reschedule',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='routine.room'),
        ),
    ]
