# Generated by Django 5.2 on 2025-06-20 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0019_remove_reschedule_offline_duration_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reschedule',
            name='status',
        ),
        migrations.AddField(
            model_name='reschedule',
            name='offline_duration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reschedule',
            name='online_duration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reschedule',
            name='room',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
