# Generated by Django 5.2.1 on 2025-06-20 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routine', '0005_remove_routine_created_at_and_more'),
        ('teachers', '0020_remove_reschedule_status_reschedule_offline_duration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classschedule',
            name='room',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='routine.room'),
        ),
    ]
