# Generated by Django 5.1.5 on 2025-06-20 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_remove_course_teachers_alter_course_total_classes'),
        ('teachers', '0020_remove_reschedule_status_reschedule_offline_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reschedule',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.course'),
        ),
    ]
