# Generated by Django 5.1.5 on 2025-06-20 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0021_reschedule_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reschedule',
            name='course',
        ),
    ]
