# Generated by Django 5.1.5 on 2025-06-20 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0023_reschedule_new_class_schedule_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reschedule',
            name='new_class_schedule',
        ),
        migrations.AlterField(
            model_name='reschedule',
            name='class_schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachers.classschedule'),
        ),
    ]
