# Generated by Django 5.1.5 on 2025-06-20 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0024_remove_reschedule_new_class_schedule_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reschedule',
            name='new_schedule',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rescheduled_from', to='teachers.classschedule'),
        ),
        migrations.AlterField(
            model_name='reschedule',
            name='class_schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='original_schedule', to='teachers.classschedule'),
        ),
    ]
