# Generated by Django 5.2 on 2025-05-31 20:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
          ('routine', '0003_slot_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassConductRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('conducted', 'Conducted'), ('rescheduled', 'Rescheduled'), ('missed', 'Missed')], max_length=20)),
                ('routine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routine.routine')),
            ],
            options={
                'unique_together': {('routine', 'date')},
            },
        ),
    ]
