# Generated by Django 5.2 on 2025-06-18 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_remove_course_teachers_alter_course_total_classes'),
        ('monitor', '0001_initial'),
        ('teachers', '0011_remove_classschedule_is_cancelled'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyClassLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('semester', models.CharField(max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('conducted', 'Conducted'), ('missed', 'Missed'), ('rescheduled', 'Rescheduled'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachers.teacher')),
            ],
        ),
        migrations.DeleteModel(
            name='ClassConductRecord',
        ),
    ]
