# Generated by Django 5.2 on 2025-04-22 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('semester', models.CharField(max_length=20)),
                ('total_classes', models.PositiveIntegerField(default=0, help_text='Total number of classes to conduct')),
            ],
        ),
    ]
