# Generated by Django 5.1.5 on 2025-06-01 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_rename_name_course_title_course_teachers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='teachers',
        ),
        migrations.AlterField(
            model_name='course',
            name='total_classes',
            field=models.PositiveIntegerField(default=22, help_text='Total number of classes to conduct'),
        ),
    ]
